version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/postgres/
    networks:
      - otasoft-mail-network

networks: 
  otasoft-mail-network:
    driver: bridge